name: jenkins-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    steps:
      - name: Trigger jenkins job
        uses: ubunturoxshacker/simple-node-js-react-npm-app@master
        with:
          url: http://49.36.191.205:8080/
          job_name: Test2
          api_token: 11835a74fcae4e2bdfd835891cfbf2fdb8
          timeout: "1000"
